version: '3.8'

services:
  # Database service
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 5073376
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3308:3306

  # Web server service
  webserver:
     image: web_image
     container_name: my-web-server-container
     environment:
       DB_HOST: db
       DB_USER: root
       DB_PASSWORD: 5073376
       DB_NAME: database_students
     ports:
       - "5000:5000"
     depends_on:
       - mysql-db

volumes: 
  db_data:
